.PHONY: build clean test

build:
#	dos2unix build_topo.sh clean_topo.sh test_topo.sh
	chmod +x build_topo.sh clean_topo.sh test_topo.sh
	bash clean_topo.sh
	bash build_topo.sh

clean:
	bash clean_topo.sh

test:
	bash test_topo.sh